# Generated by Django 4.2.4 on 2024-02-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_patient_fk_recpt_alter_patient_user_alter_recpt_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recpt',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='recpt',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tec',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tec',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
