# Generated by Django 4.2.4 on 2024-03-02 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_recpt_first_name_recpt_last_name_tec_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recpt',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recpt_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
