# Generated by Django 4.2.4 on 2023-10-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_recpt_tec_remove_tecprofile_user_delete_recptprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recpt',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='recpt',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tec',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tec',
            name='last_name',
        ),
    ]
