# Generated by Django 4.2.4 on 2023-10-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_remove_recpt_first_name_remove_recpt_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='tec',
            name='crm',
            field=models.CharField(max_length=16),
        ),
    ]
