# Generated by Django 4.2.4 on 2024-03-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_alter_patient_user_alter_tec_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cell',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recpt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tec',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
