# Generated by Django 4.2.4 on 2023-10-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_alter_customuser_cpf_alter_tec_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
