# Generated by Django 4.2.4 on 2024-02-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_alter_customuser_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_patient_user',
        ),
        migrations.AddField(
            model_name='tec',
            name='first_name',
            field=models.CharField(default='tec', max_length=30),
        ),
        migrations.AddField(
            model_name='tec',
            name='last_name',
            field=models.CharField(default='tec', max_length=30),
        ),
    ]
