# Generated by Django 5.0.3 on 2024-03-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_patient_cell_patient_created_at_recpt_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tec',
            name='crm_state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tec',
            name='crm',
            field=models.CharField(max_length=6),
        ),
    ]
