# Generated by Django 4.2.4 on 2024-02-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_customuser_crm'),
    ]

    operations = [
        migrations.AddField(
            model_name='recpt',
            name='first_name',
            field=models.CharField(default='tec', max_length=30),
        ),
        migrations.AddField(
            model_name='recpt',
            name='last_name',
            field=models.CharField(default='tec', max_length=30),
        ),
    ]
