# Generated by Django 4.2.4 on 2024-02-24 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_recpt_first_name_recpt_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='recpt_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.recpt'),
        ),
    ]
