# Generated by Django 4.2.4 on 2024-02-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_usertype_remove_patient_user_patient_fk_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
