# Generated by Django 4.2.4 on 2024-02-27 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to='lab/backup_imgs/')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('cpf', models.CharField(max_length=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='', upload_to='lab/reports/')),
                ('fk_tec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.tec')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DetectedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_img', models.ImageField(blank=True, default='', upload_to='lab/detects/')),
                ('total_wbc', models.IntegerField(default=0)),
                ('total_rbc', models.IntegerField(default=0)),
                ('total_platelets', models.IntegerField(default=0)),
                ('total_detects', models.IntegerField(default=0)),
                ('concentration_rbc', models.FloatField(default=0.0)),
                ('concentration_wbc', models.FloatField(default=0.0)),
                ('concentration_platelets', models.FloatField(default=0.0)),
                ('concentration_wbc_rbc', models.FloatField(default=0.0)),
                ('media_diam_rbc', models.FloatField(default=0.0)),
                ('media_diam_wbc', models.FloatField(default=0.0)),
                ('media_circun_rbc', models.FloatField(default=0.0)),
                ('media_circun_wbc', models.FloatField(default=0.0)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
            ],
        ),
    ]
