# Generated by Django 4.2.4 on 2024-03-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='cpf',
            field=models.CharField(max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
