# Generated by Django 4.2.4 on 2023-11-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_detectionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_img', models.ImageField(blank=True, default='', upload_to='lab/detects')),
            ],
        ),
        migrations.DeleteModel(
            name='DetectionResult',
        ),
    ]
