# Generated by Django 4.2.4 on 2023-11-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_alter_detectedimage_detected_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedimage',
            name='average_size',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='detectedimage',
            name='total_plaquetas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectedimage',
            name='total_rbc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectedimage',
            name='total_wbc',
            field=models.IntegerField(default=0),
        ),
    ]
