# Generated by Django 4.2.4 on 2023-11-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_remove_detectedimage_average_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedimage',
            name='concentracao_plaquetas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectedimage',
            name='concentracao_rbc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='detectedimage',
            name='concentracao_wbc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectedimage',
            name='concentracao_wbc_rbc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectedimage',
            name='media_circun_rbc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectedimage',
            name='media_circun_wbc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectedimage',
            name='media_diam_rbc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectedimage',
            name='media_diam_wbc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectedimage',
            name='total_deteccoes',
            field=models.IntegerField(default=0),
        ),
    ]
