# Generated by Django 4.2.4 on 2023-11-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_detectedimage_concentracao_plaquetas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedimage',
            name='media_circun_wbc',
        ),
        migrations.AlterField(
            model_name='detectedimage',
            name='concentracao_plaquetas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detectedimage',
            name='concentracao_wbc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detectedimage',
            name='concentracao_wbc_rbc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detectedimage',
            name='media_circun_rbc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detectedimage',
            name='media_diam_rbc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detectedimage',
            name='media_diam_wbc',
            field=models.FloatField(default=0.0),
        ),
    ]
