# Generated by Django 4.2.4 on 2023-11-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_remove_detectedimage_media_circun_wbc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedimage',
            name='media_circun_wbc',
            field=models.FloatField(default=0.0),
        ),
    ]
