# Generated by Django 4.2.4 on 2024-02-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_detectedimage_media_circun_wbc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectedimage',
            old_name='concentracao_plaquetas',
            new_name='concentration_platelets',
        ),
        migrations.RenameField(
            model_name='detectedimage',
            old_name='concentracao_rbc',
            new_name='concentration_rbc',
        ),
        migrations.RenameField(
            model_name='detectedimage',
            old_name='concentracao_wbc',
            new_name='concentration_wbc',
        ),
        migrations.RenameField(
            model_name='detectedimage',
            old_name='concentracao_wbc_rbc',
            new_name='concentration_wbc_rbc',
        ),
        migrations.RenameField(
            model_name='detectedimage',
            old_name='total_deteccoes',
            new_name='total_detects',
        ),
        migrations.RenameField(
            model_name='detectedimage',
            old_name='total_plaquetas',
            new_name='total_platelets',
        ),
    ]
