# Generated by Django 4.2.4 on 2024-02-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_rename_concentracao_plaquetas_detectedimage_concentration_platelets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to='lab/backup_imgs/')),
            ],
        ),
    ]
