# Generated by Django 4.2.4 on 2024-02-24 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_usertype_remove_patient_user_patient_fk_user_type_and_more'),
        ('lab', '0013_backupimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='fk_tec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.tec'),
        ),
    ]
